version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - "32768:5432"
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef